[package]
name = "code-test"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["macros"] }
sha2 = "0.10.8"
tokio = { version = "1.44.1", features = ["full"] }
